#! /usr/bin/perl
use 5.010;
use strict;
use warnings;

use Reader::Pentominoes;
use Solver::DancingLinks;

my $body = join '', <>;

my $reader = Reader::Pentominoes->new(
    header => {},
    body   => $body,
);

my $solver = Solver::DancingLinks->new(
    matrix => $reader->matrix,
    writer => $reader->writer,
);

$solver->solve();
